### ISSUE TITLE
웹 서버 로깅을 설정한다

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-pium#160]
# 어떤 이슈인가요?
다음과 같은 상황을 고려할 수 있다.
- 비정상적인 요청에 대한 시나리오 확인
- 디도스 공격과 같은 웹 접속 요청에 대한 악성 접근에 대한 웹 로그 확인

서버에 오는 요청들에 대해 로깅을 수행한다.

**Comment by Kim0914** [comment]
[팀 블로그 - Logback을 이용한 운영 환경 별 로그 남기기](https://pium-official.github.io/server-logging/)
