### ISSUE TITLE
식물 조회 시 정보 없음이 뜨는 문제 

### ISSUE THREAD

**Issue by Cl8D** [woowacourse-teams/2023-pium#196]
# 어떤 버그인가요?
- 식물에 대한 상세 조회 시 정보 없음으로 뜨는 문제가 있어요! 

## 예상 결과
- 정보가 없다면 해당 문장에 대해서 아예 띄워지지 않았으면 좋겠어요!

## 실제 결과
- 정보없음이라고 뜹니다!

## 스크린샷
![image](https://github.com/woowacourse-teams/2023-pium/assets/46810837/1da34260-2120-40aa-909a-2ddc8dca516c)

# 버그를 재현하는 방법

1. 식물 이름 검색
2. 조회하기

# 어떤 환경에서 발생했나요?

- mac OS (chrome browser)

**Comment by Choi-JJunho** [comment]
실제로 공공데이터에서 제공하지 않는 정보에 대해서 "정보없음"으로 제공하고 있습니다.
정보가 없는 경우 view에서 보이지 않게 하는 방법도 생각해볼 수 있겠네요

**Comment by Choi-JJunho** [comment]
논의완료

연관 discussion
- https://github.com/woowacourse-teams/2023-pium/discussions/211
