### ISSUE TITLE
식물 정보 수정 후 물주기 날짜가 잘못 표기되는 오류

### ISSUE THREAD

**Issue by Cl8D** [woowacourse-teams/2023-pium#197]
# 어떤 버그인가요?
- 물주기 날짜가 잘못 표기되는 것 같아요!

## 예상 결과
- 수정된 결과에 따라서 물주기 날짜도 함께 업데이트가 되어야 할 것 같습니다.

## 실제 결과
- 물주기 날짜를 수정하더라도 '다음 물주기' 날짜가 변경되지 않아요!

## 스크린샷
![스크린샷 2023-08-07 오후 2 02 05](https://github.com/woowacourse-teams/2023-pium/assets/46810837/2ddad52c-f4f3-457a-82a4-6b328036d6ac)

# 버그를 재현하는 방법
1. 식물 조회
2. [정보 수정하기] 클릭
3. 물 주기 날짜 수정
4. [다시 저장하기] 클릭

# 어떤 환경에서 발생했나요?
- macOS (chrome browser)

**Comment by Choi-JJunho** [comment]
물 주기 날짜를 수정하더라도 '다음 물주기' 날짜가 변경되지 않는것은 정상적인 동작입니다.

물 주기 값은 `타임라인 상에서 물주기 버튼을 눌렀을 때 증가하는 주기`에 대한 설정입니다.
해당 기능에 대해서 다음과 같은 조치를 취할 수 있을 것 같습니다.

- 툴팁 혹은 시작하기 페이지를 통해 사용자에게 기능에 대한 명확한 설명을 제공한다.
- 보다 직관적인 네이밍을 사용한다.

팀 내 협의 후 조치하겠습니다

**Comment by Choi-JJunho** [comment]
물주기 날짜를 수정 시 다음 물주기 날짜를 변경한다.
로 결론지었습니다.
프론트, 백엔드 모두 해당 이슈 연관지어주세요~
