### ISSUE TITLE
[BUG] 마지막 물주기 날짜 지정할때...

### ISSUE THREAD

**Issue by aiaiaiai1** [woowacourse-teams/2023-pium#199]
# 어떤 버그인가요?
식물정보에서 마지막 물주기 날짜를 지정할때 식물의 생년월일보다 더 늦게 지정이 가능합니다

## 예상 결과

- 마지막 물주기 날짜를 지정할때는 생년월일 이후로 부터 지정이 가능하는걸로 예상

## 실제 결과

- 마지막 물주기 날짜를 지정할때 생년월일 이전도 지정이 가능했음

## 스크린샷

<img width="813" alt="image" src="https://github.com/woowacourse-teams/2023-pium/assets/103165859/41b251e6-43ca-4991-8b12-7545398f70c4">

# 버그를 재현하는 방법

1. Go to '내식물.'
2. Click on '+'
3. 설정정보 저장중...

# 어떤 환경에서 발생했나요?

- 브라우저 및 버전:  크롬
- 기기 및 OS:  맥os

**Comment by Choi-JJunho** [comment]
기획상 다음과 같은 상황을 고려하여 정상적인 동작으로 판단합니다.

- 식물원 혹은 꽃집에서 분양을 받을 때 마지막으로 물을 준 날이 입양일보다 이전일 수 있습니다.
