### ISSUE TITLE
물 주기 변경 시 폼에서 UI 버그

### ISSUE THREAD

**Issue by inyeong-kang** [woowacourse-teams/2023-pium#202]
# 어떤 버그인가요?
* 물 주기를 변경했을 경우 다음 물 주기가 정상적으로 변경되지 않습니다.

## 예상 결과
* 물 주기를 변경하면 다음 물 주기 UI가 즉각 업데이트되도록 합니다.

## 실제 결과
* 물 주기를 변경하고 저장하기를 눌러야 다음 물 주기가 정상적으로업데이트됩니다.

## 스크린샷
![pium_bug2](https://github.com/woowacourse-teams/2023-pium/assets/81199414/bb7896e7-f542-4840-b77a-340e06e8745b)

# 버그를 재현하는 방법

1. 하단바에서 '내 식물' 클릭
2. 특정 식물 클릭
3. 정보 수정하기 클릭
4. 물 수정하기 input 변경

# 어떤 환경에서 발생했나요?
- Chrome
- macOS Monterey, Window10

**Comment by inyeong-kang** [comment]
다른 팀의 팀원 분이 이미 리포팅 해주셔서 이 이슈는 닫아주셔도 될거 같아요!!

**Comment by WaiNaat** [comment]
#197 과 같은 맥락입니다 👍
