### ISSUE TITLE
마지막 물을 준게 88878일 전인데 45870일 전에 데려온게 가능합니다

### ISSUE THREAD

**Issue by dladncks1217** [woowacourse-teams/2023-pium#204]
# 어떤 버그인가요?

- 마지막 물을 준게 88878일 전인데 45870일 전에 데려왔대요

## 예상 결과

-

## 실제 결과

-

## 스크린샷

<img width="528" alt="스크린샷 2023-08-07 오후 2 25 40" src="https://github.com/woowacourse-teams/2023-pium/assets/45068522/95e5b765-a37b-4886-b0b2-a7dcae1d2ea2">

# 버그를 재현하는 방법

# 어떤 환경에서 발생했나요?

- 브라우저 및 버전: 
- 기기 및 OS:

**Comment by WaiNaat** [comment]
#199 와 같은 맥락입니다
