### ISSUE TITLE
최저온도 데이터에 대한 문제

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-pium#212]
# 어떤 버그인가요?

- 최저온도 0도 이하라는 결과가 이상함

## 예상 결과

- 0도 이상이라는 문구

## 실제 결과

`적어도 "0℃ 이하" 에서 키워야 해요!`

## 스크린샷

<img width="379" alt="image" src="https://github.com/woowacourse-teams/2023-pium/assets/49794401/ec36924b-6235-4e41-acce-4680f5d6465d">

## 조치 사항

- DB 데이터 전처리를 수행한다.
  - 데이터에서 `이상`, `이하` 문구 제거

**Comment by Kim0914** [comment]
적용 완료 했습니다.

```sql
UPDATE dictionary_plant
SET `minimum_temp` = REPLACE(`minimum_temp`, '이하', '')
WHERE `minimum_temp` LIKE '%이하%';

UPDATE dictionary_plant
SET `minimum_temp` = REPLACE(`minimum_temp`, '이상', '')
WHERE `minimum_temp` LIKE '%이상%';
```
