### ISSUE TITLE
반려 식물을 등록할 때 모달로 사전 정보를 보여준다

### ISSUE THREAD

**Issue by bassyu** [woowacourse-teams/2023-pium#267]
# 어떤 이슈인가요?

반려 식물을 등록할 때 모달로 사전 정보를 보여줘야 합니다.

**Comment by WaiNaat** [comment]
해당 이슈 진행하실 때 아래 부분도 같이 부탁드려요 👍 
- 식물 등록 페이지에서 뒤로 가기의 트리거
- 최종 양식 제출 전 닉네임에 trim 적용해서 보내기
- (선택 사항) 일반 텍스트 입력에서 엔터 누르면 다음으로 넘어가기

**Comment by bassyu** [comment]
좋아요!! 확인 감사합니다~
