### ISSUE TITLE
Lambda@Edge 를 이용한 이미지 요청 개선

### ISSUE THREAD

**Issue by WaiNaat** [woowacourse-teams/2023-pium#331]
# 어떤 이슈인가요?

CloudFront에 Lambda@Edge를 적용해서 이미지 캐싱 시도

# 대략적인 순서

1. 사진 요청 시 쿼리파라미터로 너비와 높이 등의 정보를 받는다.
2.  해당 쿼리파라미터를 이용하여 이미지 크기를 조정하고 webp 확장자로 변형한 후 캐싱한다.
3. 추후 같은 쿼리파라미터로 요청이 들어오면 캐시한 값을 돌려준다.

**Comment by hozzijeong** [comment]
사용 제한이지 않나요?!?!

**Comment by WaiNaat** [comment]
슬랙에 토미께서 주신 답변은 아래와 같아서 도전해보려구요
> 추후에 실제로 겪은 문제 상황이 있는 경우, 이를 바탕으로 자료를 정리하여 다시 검토 요청하시면 다시 답변 드리겠습니다.

**Comment by WaiNaat** [comment]
실패
