### ISSUE TITLE
모두의 정원 등록 페이지

### ISSUE THREAD

**Issue by bassyu** [woowacourse-teams/2023-pium#338]

**Comment by WaiNaat** [comment]
- [ ] id가 주어지지 않은 default url은 내 식물 선택 페이지 먼저
- [ ] 난이도 선택
- [ ] 내용 입력 (글자수도 제한하기)
- [ ] 환경 정보 즉석 수정
- [ ] 반려 식물 상세 정보에 등록 버튼 추가
