### ISSUE TITLE
이미지 전송시 타입을 설정한다.

### ISSUE THREAD

**Issue by hozzijeong** [woowacourse-teams/2023-pium#369]
# 어떤 이슈인가요?
이미지 전송시 415에러를 방지한다. 
https://www.jeong-min.com/31-formdata/ 참조할 것

**Comment by WaiNaat** [comment]
![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/bd6ad4fe-5566-4f19-b5a3-be1b7a8a7ec7)
