### ISSUE TITLE
각종 리팩터링 모음

### ISSUE THREAD

**Issue by hozzijeong** [woowacourse-teams/2023-pium#388]
# 어떤 이슈인가요?
- [ ] 인풋에 line-height 추가하기
- [ ] 셀렉트 박스 위치를 계산해서 나타나는 방향 변경하기
- [ ] 달력 컴포넌트에 date-picker 추가하기
- [ ] 모달창 open시에 scroll 방지

**Comment by WaiNaat** [comment]
- [ ] 모두의 정원 목록 하단에 margin 추가
