### ISSUE TITLE
무중단 배포환경을 구성한다

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-pium#397]
# 어떤 이슈인가요?

서비스를 배포하는 중간에도 사용자는 서비스를 계속해서 사용할 수 있어야 한다.

다음 3가지 방식에 대해 알아보고 적절한 방식을 선택하여 무중단 배포 환경을 구성한다.

- 롤링(Rolling) 배포
- Blue/Green 배포
- 카나리 배포

## 추가 고려사항

- [x] #398

# 참고

- https://tecoble.techcourse.co.kr/post/2022-11-01-blue-green-deployment/
- https://hudi.blog/zero-downtime-deployment/

**Comment by Kim0914** [comment]
[멋있게 완료😎](https://blog.pium.life/dont-stop-deploy/)
