### ISSUE TITLE
husky를 통해 커밋 단위 테스트 자동화

### ISSUE THREAD

**Issue by bassyu** [woowacourse-teams/2023-pium#9]
# 어떤 이슈인가요?

이전에 webpack.config에 오류가 있었지만, 
보이지 않아서 머지한 후 다시 오류 수정 이슈를 만든 적이 있습니다.

이러한 일을 막기 위해 커밋 단위 테스트를 적용하는 것이 좋아보입니다.

**Comment by WaiNaat** [comment]
지금은 유효한 테스트가 없으니 일단 `lint` 검사를 하는 건 어떨까요?
